### ISSUE TITLE
Layout: Jetzt Padeln / Abos

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#10]
Kann umgesetzt werden. Layout liegt auf der Dropbox. Die Tabelleninhalte werden wohl nochmal geringfügig angepasst, das sollte jetzt aber nicht aufhalten. - Achtung: Ich habe noch eine falsche Telefonnummer im Layout.

Dateiname in 01_Layouts: MoCo-Walls_padel-content_hau-rein-abos.jpg

**Comment by debueb** [comment]
was mir bei der Tabelle aus User Sicht fehlt: Wie viel % oder EUR spare ich denn nun bei welchem Abo? Eine zusätzliche Spalte Ersparnis wäre doch gut oder?

**Comment by Moryson** [comment]
Hast Du Recht. Oder nen ausgerechneten Einzelstundenpreis ...
Ich schreibe das den Jungs. Die Tabelle ist aber, wie gesagt, eh noch ein bisschen eine Baustelle. Ich finde auch die Centbeträge bei nem 700€-Abo doof ...

**Comment by debueb** [comment]
done
