### ISSUE TITLE
Unterschiedliche Schriftstärken im Fließtext

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#11]
Bitte nochmal alle Seiten kontrollieren, ob die Schrift einheitlich ist.

**Beispiel fetter Fließtext:** https://walls.pro-padel.de/page/PHILOSOPHIE **(falsch)**
**Beispiel dünner Fließtext:** https://walls.pro-padel.de/matchoffers **(richtig)**

**Comment by debueb** [comment]
bold auf allen academy seiten entfernt.
