### ISSUE TITLE
Köln-Liga - Aktionsbox

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#12]
Bitte bei der Köln Liga noch unter dem Bild eine Textbox einbinden.
Grafik für die Farbinfo hängt an.
Text:
Competition, Baby! (Header gelb)
Jetzt anmelden zur Köln-Liga. (Unterzeile weiß)
Telefonnummer (Linkblock)
walls@padel.de (Link mit Betreff "Köln Liga")

![texte](https://cloud.githubusercontent.com/assets/21307800/18057138/05363174-6e0f-11e6-8d21-57643b7e15e5.jpg)

**Comment by debueb** [comment]
done
