### ISSUE TITLE
NRW-Liga - Aktionsbox

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#13]
Bitte bei der NRW Liga noch unter dem Bild eine Textbox einbinden.
Grafik für die Farbinfo wie bei Köln-Liga
Text:
Competition, Baby! (Header gelb)
Alle Infos zur NRW-Liga. (Unterzeile weiß)
URL (Link zur NRW-Liga - ggf sinnvoll gekürzt.)

**Comment by dwissk** [comment]
gibt noch keine eigene URL für die NRW Liga...

**Comment by Moryson** [comment]
Auch nicht extern?

Jan Moryson

Moryson & Co.
Markenbildung und Kommunikation

Mayer-Alberti-Str. 11
56070 Koblenz

Fon 0261 - 8896648-3
Fax     0261 - 8896648-4

jm@moryson.co
www.moryson.co

**Comment by dwissk** [comment]
Nein

**Comment by debueb** [comment]
done
