### ISSUE TITLE
Platzbuchungen verschwinden

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#14]
Ich habe schon mehrfach Platzbuchungen für kommendes Wochenende und nächste Woche eingegeben, die verschwinden immer wieder.

**Comment by debueb** [comment]
Danke Richi, dass Du das rechtzeitig gemerkt hast 😓 

Das Problem hat sich mit der relativ neuen "Bezahlt checkbox" eingeschlichen.

![screen shot 2016-08-30 at 09 38 08](https://cloud.githubusercontent.com/assets/1895897/18080369/9266028c-6e95-11e6-8732-6f72de31b45a.png)

Hintergrund ist, dass das System automatisch alle nicht bezahlten Buchungen killt. Das kann z.B. passieren, wenn jemand beim Buchungsprozess kurz vorm Bezahlen einfach den Browser schliesst. Der Platz muss nämlich bereits vorm Bezahlen geblockt werden, um Doppelbuchungen zu vermieden.
Wenn ein Platz nicht bezahlt wurde, wird er nach 30min automatisch wieder freigegeben. Und hier habe ich leider einfach vergessen, Reservierungen von dieser Regel auszunehmen. Daher wurden, wie Du vielleicht gemerkt hast, auch nicht alle Reservierungen gelöscht. Konkret wurden die Reservierungen, bei denen die "Bezahlt" Checkbox gesetzt wurde, nicht gelöscht. Bei einer Reservierung sollte diese Checkbox aber keinen Einfluss darauf nehmen, sie dient lediglich der Nachvollziehbarkeit für den Admin. Dieser Fehler ist nun korrigiert.
