### ISSUE TITLE
Zeitangabe bei Buchungen

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#15]
Wenn ich eine Uhrzeit bei der Platzreservierung eingebe, erscheint in der Zeittafel des betreffenden Tages eine andere Uhrzeit. 
Beispiel: Dienstag Abo September-Februar 19:30-21:00 wird als 19:00-21:00 angezeigt. 
Beispiel: Samstag 03.09. 10:00-12:00 wird als 9:30-12:0 angezeigt

**Comment by debueb** [comment]
Das liegt daran, dass die "Zeittafel" auf den Buchenden zugeschnitten ist. Wenn Du eine Reservierung von 9:30-11:00 vornimmst, dann kann ab 9:00 der Platz nicht mehr gebucht werden, da die min. Spieldauer 60min beträgt. Wenn Du auf den info button klickst, siehst Du aber die genaue Buchungszeit.
![screen shot 2016-08-30 at 09 50 15](https://cloud.githubusercontent.com/assets/1895897/18080803/430f7946-6e97-11e6-8ae7-fa5fefa68fa7.png)
