### ISSUE TITLE
Eingabe von events

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#16]
Bei der Eingabe von events treten Probleme auf:
1. Das event müsste einer Kategorie zugeordnet werden können (Liga oder Turnier)
2. Wenn ich versuche eine Buchungseinstellung für dieses Event zu definieren, kollidiert diese immer mit der "normalen" Buchungseinstelung für den betreffenden Tag. Schätze das Problem liegt hier daran, dass die Funktion "Event buchen" an den Kalender gekoppelt ist und nicht an das Event.
3. Ich würde gerne einem Event erstmal nur einen Namen geben "#wallsCGN Playday", dann Kategorien (Damen, Herren, Mixed) und dann den Spielern die Möglichkeit geben sich zu den angegebenen Bedingungen anzumelden. 

Vielleicht schaffen wir es noch dieses Tool einmal gemeinsam durchzugehen.

**Comment by debueb** [comment]
1. Der Event Typ bestimmt die Art des Events, also ob es ein Turnier oder ein Liga Event ist.
2. Ich vermute, dass Du auch die Angebote "Padel Platz 1..." mit ausgewählt hast. Du kannst ein Angebot nicht 2x zum gleichen Zeitpunkt anbieten.
3. Das kannst Du z.Z. mit eigenen Content Seiten abbilden. Konkret heisst dass, dass Du eine eigene Content Seite für jedes Event erstellst und dort die Kategorieren darstellst und zu den einzelnen Events verlinkst. Ich rate davon aber ab, da das sehr viel Content Pflege mit sich bringt. 
   Stand heute ist: Du gibst jedem Event einen eindeutigen Namen, z.B. SPLC Herren Padelfaktor 13 Oktober. Der Eventtyp wäre "Pull (Jeder mit jedem, rundenbasiert)". Alle Events mit diesem Typ werden dann automatisch unter /events/SPLC gelistet, so dass die lästige und fehleranfällige Content Pflege entfällt. Wenn Du einzelne Turniere noch weiter gruppieren möchtest, können wir darüber nachdenken, z.B. Event Gruppen einzuführen...
   3b (online anmelden). Das geht prinzipiell, wenn man alles richtig einstellt.

Ich sehe, dass hier noch ein Klärungsbedarf besteht. Es ist zugegebenermaßen auch nicht alles selbsterklärend. Daher müssen wir das nochmal zusammen durchgehen.
