### ISSUE TITLE
Löschen eines Angebots

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#17]
Ich habe wegen der Turniereinstellung einiges versucht und blöderweise ein Angebot erstellt, das ich nun nicht mehr löschen kann, weil "erst alle Referenzen dazu gelöscht werden müssen". Schaffe ich nicht, bitte wieder rausnehmen den #wallsCGN...

**Comment by debueb** [comment]
In diesem konkreten Fall hattest Du "wallsCGN..." einer Angebotsgruppe "Turnierteilnahme" zugeordnet. Diese Zuordnung musste erst aufgehoben werden.

Tipp: Bei Angeboten, die nicht über das Buchungstool (sonder über die Event Seite) buchbar sein sollen, kannst Du den Haken bei "Im Buchungskalender anzeigen" raus nehmen.

![screen shot 2016-08-30 at 10 09 35](https://cloud.githubusercontent.com/assets/1895897/18081363/18bda192-6e9a-11e6-8937-3344e3f96b6a.png)
