### ISSUE TITLE
Spieler anlegen

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#27]
Wenn ich als Admin einen Spieler anlege . wie kommt er an seine Daten und wie kann er sie vervollständigen? Ich habe walls GmbH angelegt und kann mich mit dem bei mir voreingestellten Passwort asdf anmelden, andere wissen das ja nicht.

**Comment by debueb** [comment]
Wenn Du einen Spieler anlegst hat er kein voreingestelltes Passwort.

Wenn sich ein Spieler registriert schaut das System, ob die Email bereits vorhanden ist. Wenn ja, dann schaut das System, ob der Spieler sich bereits registriert hat. Wenn das der Fall ist, dann wird eine entsprechende Fehlermeldung ausgegeben. Wenn nein, dann werden die Daten des Spielers, die Du eingegeben hast, in die Registrierungsmaske übernommen und er kann die Registrierung vervollständigen.
