### ISSUE TITLE
Zurücksetzen des Passworts

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#28]
Ich wusste das Passwort meines (als Admin) neu angelegten Kontos walls GmbH nicht, habe mal auf den Passwort zurücksetzen Button geklickt und eine Email bekommen. Der Link war nicht "aktiv", ich musste die Zeile kopieren und in den Browser einfügen, habe aber kein neues "neutrales" Passswort bekommen.

**Comment by debueb** [comment]
Vom Admin generierte Accounts haben kein voreingestelltes Passwort. 

Es gibt kein neutrales Passwort. Der Nutzer bestimmt das Passwort.
