### ISSUE TITLE
Sicherheitslücke

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#30]
Wenn ich NICHT EINGELOGGT über die Weichenseite auf der Padelseite lande und dann Login/Registrierung auswähle, kann ich NICHT EINGELOGGT auf die Admin-Funktionen zugreifen.

**Comment by debueb** [comment]
du bist bei der Seite so lange eingeloggt, bis du dich ausloggst. auch wenn du den browser schliesst und dann neu über die weichenweite gehst... bitte screenshot anhängen, dass du nicht eingeloggt auf admin Funktionen zugreifen kannst.... ansonsten gehe ich sehr stark davon aus, dass du noch eingeloggt bist.

**Comment by Richiwalls** [comment]
ich habe jetzt nochmals versucht. Definitiv ausgeloggt und komischerweise komme ich immer als Patrick Pihan eingeloggt wieder an. Nach dem Klick auf einloggen zeigt die Kopfleiste "ausloggen" und "Admin" an.
