### ISSUE TITLE
Bearbeiten-Symbole

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#31]
![screenshot homepage 1](https://cloud.githubusercontent.com/assets/20799226/18122084/fe30f260-6f67-11e6-9562-6c50b5d5e2c4.jpg)

HIer sind unter dem "Admin" Symbole die da nicht hingehören

**Comment by debueb** [comment]
Die Bearbeiten Symbole dienen als Shortcut zur Bearbeitung des jeweiligen Blocks. Endnutzer sehen diese Symbole nicht.
