### ISSUE TITLE
Admin Login Problem besteht weiter

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#32]
Ich habe das jetzt nochmal versucht, definitiv ausgeloggt, ich komme immer wieder nach dem Klick auf Login/Reservierung als Patrick Pihan eingeloggt wieder an

**Comment by debueb** [comment]
Ich kann das Problem jetzt nachvollziehen. Man bleibt quasi dauerhaft eingeloggt, der Logout funktioniert also nicht. Welchen Browser nutzt Du?

**Comment by Richiwalls** [comment]
Firefox

**Comment by debueb** [comment]
Das Logout Problem ist nun behoben.
