### ISSUE TITLE
Academy / Team: Trainer-Kacheln nur im Contentbereich

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#34]
im Moment fliegt die Seite noch etwas auseinander. Bekommst du die Kacheln so eingefangen, dass eine Zeile immer die Breite des Contents hat - also dass die Zeilen immer mit dem transparenten Block obendrüber abschließen?

**Comment by debueb** [comment]
So sieht es aktuell aus (1)
![screen shot 2016-09-02 at 09 48 56](https://cloud.githubusercontent.com/assets/1895897/18196579/8951bbdc-70f2-11e6-801e-b5a806d18bfa.png)

Das was Du anfragst hatte ich so am Anfang. Patrick wollte dann auf seiner Bildschirm Auflösung (vermutlich 1024px) 3 anstatt 2 Kacheln pro Zeile. Daher habe ich mehr Kacheln pro Zeile erlaubt, so dass die Kacheln bei gewissen Bildschirmauflösungen breiter sind als der restliche Inhalt.

Das Problem an der Sache ist folgendes: Die Bilder haben eine festes Seitenverhältnis. Wenn ich die Kacheln auf die gesamte Content Breite ziehe, dann passt das Seitenverhältnis nicht: (2)

![screen shot 2016-09-02 at 09 39 02](https://cloud.githubusercontent.com/assets/1895897/18196408/7d7a2408-70f1-11e6-8409-181e689a3e9d.png)

Daher zeigt man häufig nur einen Ausschnitt des Bildes. Sieht aber in diesem Fall auch nicht gut aus: (3)

![screen shot 2016-09-02 at 09 38 30](https://cloud.githubusercontent.com/assets/1895897/18196427/94492d0a-70f1-11e6-84a5-9a9ba38a49d1.png)

So sah es am Anfang aus: (4)

![screen shot 2016-09-02 at 09 30 58](https://cloud.githubusercontent.com/assets/1895897/18196462/d3b918d8-70f1-11e6-94d6-874ada9d4b67.png)

Alternativ kann ich folgene Lösungen anbieten: Seitenverhältnis beibehalten, Inhalt zentrieren und leeren Platz auffüllen: (5)

![screen shot 2016-09-02 at 09 26 59](https://cloud.githubusercontent.com/assets/1895897/18196485/fb29699a-70f1-11e6-88da-3142d6597d13.png)

Leeren Platz gleichmässig zwischen den einzelnen Kacheln verteilen: (6)

![screen shot 2016-09-02 at 09 29 12](https://cloud.githubusercontent.com/assets/1895897/18196522/2ca40304-70f2-11e6-8368-2569a8757fc2.png)

Alles linksbündig: (7)

![screen shot 2016-09-02 at 09 30 19](https://cloud.githubusercontent.com/assets/1895897/18196528/38e227f4-70f2-11e6-86ac-ac45e1192c38.png)

Alles nach aussen: (8)

![screen shot 2016-09-02 at 09 30 42](https://cloud.githubusercontent.com/assets/1895897/18196545/4e6fd4f4-70f2-11e6-9eed-277c7c137a81.png)

Wie man es dreht und wendet, für dieses Problem gibt es meiner Meinung nach keine optimale Lösung. Ich bin für (1), (4) oder (5)

**Comment by Moryson** [comment]
Hi,
ich fände die Nummer 5 gut, wenn 
- die Kästen tatsächlich rechts und links bündig zum oberen Kasten säßen
- der letzte, einzeln stehende Kasten nicht breiter wäre, als die einzelnen Kästen in den Zeilen darüber.
- wir breitere Fotos einbinden können, die die Kacheln auch so noch ausfüllen. - Wenn die Kacheln dann wieder schmaler werden, kann ja rechts und Links was abgeschnitten werden. ich sehe dann zu, dass die Köpfe immer zentriert sind.
  (Beispiel-Foto im Anhang)

was meinst Du?

Viele Grüße,
Jan

Jan Moryson

Moryson & Co.
Markenbildung und Kommunikation

Mayer-Alberti-Str. 11
56070 Koblenz

Fon 0261 - 8896648-3
Fax     0261 - 8896648-4

jm@moryson.co
www.moryson.co

**Comment by dwissk** [comment]
Wenn Du auf ein Github Issue mit Anhang antwortest, wird der Anhang leider nicht automatisch im Github Issue erstellt. Aber ich kann mir vorstellen, was Du meinst. Müsste gehen.

**Comment by Moryson** [comment]
Hi, Datei liegt auch auf der Dropbox.

Jan Moryson

Moryson & Co.
Markenbildung und Kommunikation

Mayer-Alberti-Str. 11
56070 Koblenz

Fon 0261 - 8896648-3
Fax     0261 - 8896648-4

jm@moryson.co
www.moryson.co

**Comment by debueb** [comment]
Läuft! Gute Idee. Bräuchte nur alle "mugshots" in der Breite, sieht sonst bei einigen Auflösung etwas komisch aus.

![screen shot 2016-09-02 at 15 44 42](https://cloud.githubusercontent.com/assets/1895897/18205816/5b905910-7124-11e6-8e6f-a95af345f196.png)

![screen shot 2016-09-02 at 15 47 42](https://cloud.githubusercontent.com/assets/1895897/18205895/aac9390c-7124-11e6-8179-7b07b9e11034.png)

**Comment by Moryson** [comment]
Bestens. Bilder liegen in der Dropbox.

Jan Moryson

Moryson & Co.
Markenbildung und Kommunikation

Mayer-Alberti-Str. 11
56070 Koblenz

Fon 0261 - 8896648-3
Fax     0261 - 8896648-4

jm@moryson.co
www.moryson.co

**Comment by debueb** [comment]
done
