### ISSUE TITLE
SEO: Seitentitel, Description und Co ...

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#37]
Kann man das irgendwo je Seite pflegen? Machst Du das in den Templates?

**Comment by debueb** [comment]
Aktuell kann man das nicht pflegen. Könnte man aber einbauen.

**Comment by debueb** [comment]
done. admin kann jetzt Titel und description pflegen. Keywords macht man nicht mehr.

**Comment by Moryson** [comment]
Bestens und Recht hast du.

Jan Moryson

Moryson & Co.
Markenbildung und Kommunikation

Mayer-Alberti-Str. 11
56070 Koblenz

Fon 0261 - 8896648-3
Fax     0261 - 8896648-4

jm@moryson.co
www.moryson.co
