### ISSUE TITLE
Google Map

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#40]
Die würde ich gerne mal ausprobieren: 
https://snazzymaps.com/style/17/bright-and-bubbly

**Comment by debueb** [comment]
<img width="839" alt="screen shot 2016-08-31 at 17 58 06" src="https://cloud.githubusercontent.com/assets/1895897/18136152/9a8e9216-6fa4-11e6-9383-4cbe3ad19323.png">

so sähe die map aus.

**Comment by Moryson** [comment]
Finde ich gut. Hatten wir Dir nicht vor längerem mal nen passenden Pin geschickt?
Müsste auch auf der Dropbox liegen.

Drunter wollten wir ja die Beiden Links "Route planen" und "In Google Maps öffnen"

Farben der Buttons wie "Don't call it"

Besten Dank,
Jan

**Comment by debueb** [comment]
ich glaube du lässt dich durch das viele blau (Wasser) auf der verlinkten map optisch täuschen... die karte oben sieht ja nicht besser aus als eine standard google maps karte. im Gegenteil werden noch die vollkommen falschen Sachen hervorgehoben...

**Comment by debueb** [comment]
done
