### ISSUE TITLE
Buchungseinstellung für Events

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#45]
Ich lege ein Event an und möchte dass die Spieler sich selber anmelden können. Dafür muss ich eine Buchugnseinstellung anlegen und auswählen. Die überschneiden sich dann aber mit schon bestehenden Buchungseinstellungen für Platzbuchungen und dann entsteht ein Durcheinander. 
Ich müsste in der Buchungseinstellung "Event" oder "Liga" oder "Turnier" angeben können. Was muss ich tun damit die Spieler sich selber anmelden können?

**Comment by debueb** [comment]
done
