### ISSUE TITLE
Eventbuchung stornieren

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#46]
Ich kriege walls GmbH nicht mehr aus der SPLC 11-12 Ladys raus, was muss ich tun?

**Comment by debueb** [comment]
es gibt aktuell einen Bug der verhindert, dass man Elemente aus der Liste entfernen kann, ohne vorher andere Elemente ausgewählt zu haben. Ich habe walls GmbH jetzt so entfernt. Ich lasse das Issue hier offen, bis der Bug behoben ist.

**Comment by debueb** [comment]
done
