### ISSUE TITLE
Eventgruppe Turnier

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#47]
Wenn ich die Kategorie #wallsCGN Playday Herren 10.09.2016 eingebe, wird die nirgends gelistet. Denke es liegt daran, dass ich zwar eine Eventgruppe "Turnier" angelegt habe, diese aber nicht verknüpft ist mit dem Reiter "Competition - Turniere". Richtig?

**Comment by debueb** [comment]
Ja genau.

Das Modul "Turniere" findest Du hier:

Admin -> Allgemein -> Module -> COMPETITION -> Submodule bearbeiten --> TURNIERE. Da dann unter Event Gruppen "Turniere" auswählen. Dann werden automatisch alle Events, die Du der Event Gruppe "Turniere" hinzufügst, unter dem Module "TURNIERE" gelistet.
