### ISSUE TITLE
Buchungen löschen/ändern

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#48]
Konkreter Fall: Morgen (Mittwoch) hat Andreas Greuel von 19:00 bis 20:30 gebucht. Er hat angerufen, wir möchten bitte seine Buchung um eine halbe Stunde nach hinten verschieben. Wie?
Generell, ich muss Buchungen löschen oder ändern können, ist wichtig.
Danke!

**Comment by debueb** [comment]
Du kannst den Nutzer darauf hinweisen, dass er bis zu 24h vor Spielstart selbst stornieren kann. 

Du kannst jetzt aber auch Buchungen als Admin löschen. Dazu in der Buchungsliste eine Buchung auswählen, dann Löschen. Danach musst du eine neue Reservierung anlegen.

Wenn ich das richtig sehe ist dann morgen bis 19:30 ein Platz frei! Komm schon Richi, vamos
