### ISSUE TITLE
Eventbuchung

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#49]
Moin, habe gerade für Patrick und mich Playday 10.09. gents gebucht. In der Buchungsbestätigung steht "Preis: 230,-". Auch dabei steht die Spieldauer, die brauchen wir hier nicht.

**Comment by debueb** [comment]
Die 230 EUR kommen daher, dass Du in der Buchungseinstellung als Min. Dauer 60Min und als Preis 20EUR angegeben hast. Start ist um 10:00, Ende um 21:30. Macht 11,5h \* 20EUR = 230EUR. 

Damit der Preis stimmt würde ich vorschlagen, in der Buchungseinstellung das Ende so einzustellen, dass der Preis passt. Sprich Ende um 11:00. Da Du die Plätze sowieso separat reservieren musst spielt die Endzeit in der Buchungseinstellung ansonsten keine Rolle.

Ich werde das System dann so anpassen, dass Endzeit und Spieldauer nicht angezeigt werden, wenn es sich um eine Turnier Buchung handelt. Der dann hoffentlich korrekte Preis bleibt aber drin, OK?

**Comment by Richiwalls** [comment]
Ja OK, wobei mir glaube ich noch lieber wäre, wenn wir den Preis so lange nicht nochmal zeigen, bis wir die BEdienung im Griff haben.

**Comment by debueb** [comment]
Spieldauer wird nicht mehr angezeigt, der Preis schon. Ich habe die Buchungseinstellungen angepasst, so dass der Preis stimmt.
