### ISSUE TITLE
Aktuelle Seite in Navigation sichtbar machen

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#5]
Wenn man auf einer Seite ist, bitte den jeweiligen Punkt gehighlightet lassen. 
Und, wenn vorhanden, die Subnavi stehen lassen, und den aktuellen Unterpunkt ebenfalls highlighten.

**Comment by debueb** [comment]
Macht Sinn, bedingt aber technische Umbauten, die etwas Zeit in Anspruch nehmen. Werde ich nachliefern müssen.
