### ISSUE TITLE
Buchungsbestätigungen...

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#50]
...landen im Spamordner, was tun?

**Comment by debueb** [comment]
aus technischer Sicht habe ich bereits alle Maßnahmen getroffen, die das verhindern. Das war vor dem Launch auch kein Problem, ich habe aber auch beobachtet, dass seit Kurzem die Emails im Spam Ordner landen. Das liegt vermutlich daran, dass die Buchenden die Mails als Spam klassifizieren, was dann wiederum in einer zentralen Spam Datenbank gemeldet wird. Da hilft nur: Email als "kein Spam" kennzeichnen.

Ich werde versuchen den Absender mal auf padel@walls.de abzuändern. Dazu erhaltet Ihr gleich eine Email mit einem Bestätigungslink. Da bitte drauf klicken, dann Bescheid geben.

**Comment by debueb** [comment]
Emails werden jetzt über padel@walls.de verschickt.
