### ISSUE TITLE
Registrierung Events

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#52]
Die Anmeldung für Turnierteilnehmer ist noch sehr umständlich. Wir haben Sorge, dass durch die Pflicht zur Registrierung Teilnehmer abgeschreckt werden. Zusätzlich müssen die Teilnehmer dann auch noch evtl. Ihre Spielpartner registrieren ,it den korrekten Daten, kann sein dass das zu umständlich ist. Außerdem wollen wir auch Einzelspielern die ANmeldung ermöglich. Diese Spieler werden dann kurzfristig vorher oder vor Ort vermittelt.

**Comment by debueb** [comment]
Das Problem ist: Vorname, Nachname und Email Adresse sind unabdingbar. Aus dem Namen der Spieler generiert sich z.B. automatisch der Team Name. Die Email Adresse dient als eindeutige Identifizierung eines Spielers. Dadurch wird z.B. verhindert, dass ein Spieler mehrfach erstellt wird. Ohne diese zwingend notwenigen Daten können viele Checks nicht durchlaufen werden, z.B. ob jemand einen Partner angibt, der bereits mit einem anderen Spieler angemeldet ist. Es kann nicht überprüft werden, ob ein Team bereits existiert, oder ob automatisch ein neues erstellt werden muss. Wenn man die Registrierung auflockert wird das unweigerlich zu Chaos führen. Spieler werden doppelt angelegt, das gleiche Team wird mehrfach existieren, das Ranking wird nicht mehr funktionieren usw. 
Darüberhinaus können Einzelspieler sich schon jetzt für Pull Events selbst anmelden. Sie müssen keinen Partner angeben, da bei einem Pull ja jeder mit jedem spielt. Aus meiner Sicht ist das gerade für den Anfang die deutlich bessere Spielvariante.

Siehe dazu auch diesen Chat:
<img width="607" alt="screen shot 2016-09-08 at 11 25 12" src="https://cloud.githubusercontent.com/assets/1895897/18346133/1393394e-75bf-11e6-86ac-ea0fc87b1425.png">
