### ISSUE TITLE
Anmelde-Button für die Köln-Ligen

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#54]
Hi Dominik! 
Hoffe dir gehts gut, lange nichts gehört... (wenn man das nach ein paar Tagen schon so sagen kann)
Wir bewerben jetzt die Köln-Liga sehr intensiv und haben festgestellt dass Spieler sich nicht selber für die Ligen anmelden können. Hatten wir das bewusst gemacht? Wenn dir da auch nichts mehr einfällt, bitte füge noch bei allen Ligen den Anmeldebutton hinzu.
Danke und viele Grüße
Richi

**Comment by debueb** [comment]
ich glaube der Grund war, dass die Nutzer nicht wissen, welchen Padelfaktor sie haben und daher nicht wissen, welche Liga sie buchen müssen und dass Ihr die Zuordnung erst einmal manuell macht, bis sich der Padelfaktor etabliert hat. Selbst wenn man seinen Padelfaktor weiss: meldet man sich für SPLC 12-13 I Oktober oder für SPLC 12-13 II Oktober an?
