### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#55]
Hi Dominik, 

komischerweise passiert immer noch folgendes:
Ich gehe mit meinem Laptop über die Weichenseite in die Padel-App und klicke auf Login (ohne irgendwelche Daten einzugeben), dann erscheint die Maske zum Login-Daten eingeben, ABER: ich bin in dem Moment schon als Patrick Pihan mit patrick@walls.de eingeloggt. Diese Zugangsdaten habe ich in meinen Einstellungen nicht gespeichert, vielleicht findest du den Fehler?!

VG
Richi

**Comment by debueb** [comment]
fixed
