### ISSUE TITLE
Abo Buchungen mit einem Klick löschen

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#56]
Ich habe ein falsches Abo eingegeben, möchte dieses nun wieder löschen. Einzeln die Stunden löschen ist sehr aufwendig. Gibt es eine Möglichkeit das zu vereinfachen und alle dazugehörigen Abostunden auf einmal zu löschen?

VG
Richi

**Comment by debueb** [comment]
Du kannst jetzt in der Buchungsliste auf eine Buchung gehen und dann "Alle Buchungen mit Kommentar 'Abo XYZ' löschen" aufrufen. Wichtig ist, dass der Kommentar eindeutig ist, da wirklich alle Buchungen mit diesem Kommentar gelöscht werden. Ich empfehle daher möglichst eindeutige Kommentare zu vergeben, sprich lieber "Abo Max Mustermann Winter 2016" als "Abo Max".

**Comment by Richiwalls** [comment]
Ok, danke, das ist schon mal einen Schritt weiter, allerdings habe ich dann folgendes Problem: Die Tennisschule Weiden bucht mehrere Abos jede Woche und im System sollte demnach auch "Tennisschule Weiden" bei den Spielterminen erscheinen. Kann man das Löschen an Kommentar, Tag, Uhrzeit und Court knüpfen? So dass dann nur die Buchungen "Tennisschule Weiden, Mittwoch, 15-16:30 Court 1" gelöscht werden?
Oder muss ich jedem Abo eine eindeutige Bezeichnung geben (wie oben)? Das wird dann auf dem Belegungsplan blöd mit der Darstellung, oder?

**Comment by debueb** [comment]
Du hast Recht, die Kommentare werden ja auch dem Endnutzer angezeigt. 

Ich habe jetzt den "Alle Buchungen mit Kommentar 'Abo XYZ' löschen" in der Buchungsliste wieder entfernt und stattdessen einen "Alle löschen" Link in der Platz Reservierung hinzugefügt.
