### ISSUE TITLE
Einzelne Matches eingeben

### ISSUE THREAD

**Issue by Richiwalls** [debueb/pro-padel#59]
Wir hatten da schonmal drüber gesprochen. Wir haben jetzt "Ergebniszettel", die wir den Leuten gerne mit auf den Platz geben wollen, egal ob Turnier, Liga oder sonstiges Match. Hast du eine Idee, wie man einzelne Matches ins System eingeben kann, damit wir den padelfaktor aktiviert bekommen?

**Comment by debueb** [comment]
| Modus | Kommentar |
| --- | --- |
| Rundenturnier (Jedes Team gegen jedes Team) | erübrigt sich, da das System automatisch für alle Spiele ein Match erstellt |
| Rundenturnier (Mannschaft gegen Mannschaft) | ist gedacht für NRW Liga, erübrigt sich daher auch, da der Claudius das auch nicht mehr pflegen will |
| Pull (Jeder mit jedem, rundenbasiert | das System erstellt automatisch Spiele, sobald eine faire Anzahl Matches (sprich jeder hat gleich viele Matches) möglich ist, also frühestens bei 4 Spielern. Zusätzlich kannst Du nun in diesem Modus einzelne Matches anlegen, da es ja leider nicht immer aufgeht |
| K.O. Turnier | Das System erstellt aus der Anzahl der Spieler automatisch das K.O. Tableau unter Berücksichtigung des Padelfaktors, dass der Admin anpassen kann, ausserdem werden Bye / Freilos Spiele automatisch vergeben, hier gibt es also auch keine Matches ausserhalb der Reihe |
| Gruppen K.O. Turnier | ähnlich K.O. Turnier |

Aus meiner Sicht passt das so.
