### ISSUE TITLE
Darstellungsfehler Chrome

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#7]
(Chrome Version 51.0.2704.103 (64-bit))
Wie schon besprochen, sind immer noch die gelbverläufe über dem Slider,[
<img width="1163" alt="bildschirmfoto 2016-08-29 um 15 22 37" src="https://cloud.githubusercontent.com/assets/21307800/18052793/a4230aae-6dfc-11e6-9989-86c47c9c5de8.png">
](url)

**Comment by debueb** [comment]
Hmmm. Die Pfeile sitzen ja auch komplett falsch. ich nutze chrome 52.0.2743.116 (64-bit) und sehe das nicht. auch nicht im ff oder safari. Du nutzt doch bestimmt einen Mac, oder? Cache geleert? Irgendeine extension aktiv?

**Comment by Moryson** [comment]
Hi, ja. Mac. Aber Cache schon beim letzten Mal brav gelehrt. Extension ist auch keine aktiv.
Ist jetzt aber auch nicht so wild. ich werde zuhause auf dem Mac mal einen ganz frischen Chrome installieren und da nochmal prüfen.

**Comment by dwissk** [comment]
Selbst IE9 kriegts gebacken 😅 Zwar ohne Schräge, aber immerhin...
<img width="1072" alt="screen shot 2016-08-29 at 16 28 22" src="https://cloud.githubusercontent.com/assets/3786617/18054819/b7b2fe22-6e05-11e6-959b-153f8ffc39a6.png">

**Comment by Moryson** [comment]
Ach der IE, niedlich :-D

**Comment by Moryson** [comment]
Sorry. Ich Depp hatte doch noch eine Extension an ... Alles gut :-)
