### ISSUE TITLE
Darstellungsfehler Firefox: Don't call it Ecke

### ISSUE THREAD

**Issue by Moryson** [debueb/pro-padel#8]
Ecke bei Don't call it Tennis fehlt.

**Comment by Moryson** [comment]
Firefox 48.0.1

<img width="1343" alt="bildschirmfoto 2016-08-29 um 16 27 52" src="https://cloud.githubusercontent.com/assets/21307800/18054888/09d9a5f2-6e06-11e6-8cfd-7007ec1dee53.png">

**Comment by debueb** [comment]
[nur zur info]
Ich nutze css clip-path anstatt einem Bild aus performance gründen. FF unterstützt das nur mit SVG url Parametern
http://www.mediaevent.de/css/clip-path.html
http://caniuse.com/#feat=css-clip-path
ToDo: SVG testen

**Comment by debueb** [comment]
svg works. done
